import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Database, GitBranch, Layers, Lock, ScrollText, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Section, SectionHeading, FeatureCard } from "@/components/marketing/section";
import { TrademarkNotice } from "@/components/shared/demo-notices";
import { APP } from "@/lib/config";

export const metadata: Metadata = {
  title: "About",
  description:
    "BrokerT is an independent Tesla-focused investment and trading platform. What it is, what it is not, and how it is built.",
};

export default function AboutPage() {
  return (
    <>
      <Section className="border-t-0">
        <SectionHeading
          eyebrow="About"
          title="An independent platform for a single instrument"
          description="Most brokerages spread themselves across ten thousand tickers and cover none of them properly. BrokerT does the opposite."
        />

        <div className="mt-10 grid gap-10 lg:grid-cols-2 lg:gap-16">
          <div className="space-y-4 text-[0.9375rem] leading-relaxed text-muted-foreground">
            <p>
              {APP.name} is built around one instrument and the tooling a focused investor actually uses:
              a real charting terminal, a working order lifecycle, a portfolio whose numbers are derived
              rather than stored, and a set of thematic strategies that state their risk before they
              state a target.
            </p>
            <p>
              It is also built to be honest about what it is. In demo mode every price is generated by a
              simulation, every balance is a record inside this application, and every screen says so.
              Nothing here pretends to be a market feed, a bank account or a brokerage relationship.
            </p>
            <p>
              The architecture assumes it will one day be connected to real infrastructure. The
              market-data layer is an interface with one implementation; the funding path is a database
              function that refuses to run outside demo mode. Replacing either is a contained change, not
              a rewrite.
            </p>
          </div>

          <Card className="space-y-5 p-6">
            <h2 className="text-sm font-semibold uppercase tracking-wide">What BrokerT is not</h2>
            <ul className="space-y-3">
              {[
                "Not affiliated with, endorsed by or operated by Tesla, Inc.",
                "Not a registered broker-dealer or investment adviser.",
                "Not a bank, money transmitter or payment institution.",
                "Not regulated, licensed or insured.",
                "Not a source of investment advice or recommendations.",
                "Not connected to any exchange, clearing house or vehicle manufacturer.",
              ].map((item) => (
                <li key={item} className="flex gap-2.5 text-sm text-muted-foreground">
                  <span className="mt-1.5 size-1.5 shrink-0 rounded-full bg-destructive" aria-hidden />
                  {item}
                </li>
              ))}
            </ul>
          </Card>
        </div>
      </Section>

      <Section className="bg-muted/25">
        <SectionHeading
          eyebrow="How it is built"
          title="Decisions that shaped the product"
          align="center"
        />
        <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          <FeatureCard
            icon={Lock}
            title="Authorisation in the database"
            description="Every table is deny-by-default under Row Level Security and scoped to the signed-in user. Hiding a page is presentation, not protection."
          />
          <FeatureCard
            icon={Database}
            title="One write path for money"
            description="Trades, allocations and funding each run inside a single transactional function that resolves prices and checks balances server-side."
          />
          <FeatureCard
            icon={Layers}
            title="Derived, never stored"
            description="Portfolio value, P/L and returns are recomputed from holdings and the current quote on every request."
          />
          <FeatureCard
            icon={GitBranch}
            title="Providers behind interfaces"
            description="Market data, email and payments each sit behind a seam so a real provider can replace the demo one without touching the product."
          />
          <FeatureCard
            icon={ScrollText}
            title="An audit trail that cannot be edited"
            description="Administrative actions append to a log that rejects updates and deletes at the database level."
          />
          <FeatureCard
            icon={Sparkles}
            title="Disclosure as a feature"
            description="Simulation, risk and the absence of any Tesla affiliation are stated on the screens where they matter, not buried in a footer."
          />
        </div>
      </Section>

      <Section>
        <div className="rounded-2xl border border-border bg-card px-6 py-10 sm:px-10">
          <h2 className="text-xl font-semibold tracking-tight">Trademarks and affiliation</h2>
          <TrademarkNotice className="mt-3 max-w-3xl text-sm" />
          <p className="mt-3 max-w-3xl text-sm leading-relaxed text-muted-foreground">
            References to Tesla, Inc. and its vehicle models on this site are nominative — they identify
            the subject of the market data and the vehicle configurations shown. They do not indicate any
            partnership, sponsorship, licence or authorisation.
          </p>
          <Button asChild className="mt-6">
            <Link href="/register">
              Open a demo account <ArrowRight />
            </Link>
          </Button>
        </div>
      </Section>
    </>
  );
}
