import type { Metadata } from "next";
import Link from "next/link";
import { Section, SectionHeading } from "@/components/marketing/section";
import { FaqAccordion, type FaqItem } from "@/components/marketing/faq-accordion";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = {
  title: "FAQ",
  description: "Answers about demo mode, market data, funding, risk and BrokerT's independence from Tesla, Inc.",
};

const GROUPS: { title: string; items: FaqItem[] }[] = [
  {
    title: "The platform",
    items: [
      {
        question: "Is BrokerT affiliated with Tesla, Inc.?",
        answer:
          "No. BrokerT is an independent platform focused on Tesla-related market data and investment tooling. It is not owned, operated, sponsored or endorsed by Tesla, Inc., and it is not an authorised Tesla dealer. Tesla and its model names are trademarks of Tesla, Inc., referenced here only to identify the subject of the data shown.",
      },
      {
        question: "Is BrokerT regulated?",
        answer:
          "No. BrokerT is not a registered broker-dealer, investment adviser, bank or money transmitter, and it is not licensed or insured. Nothing on the platform is an offer to buy or sell any security.",
      },
      {
        question: "Is anything on the platform investment advice?",
        answer:
          "No. Everything shown is information and tooling. Nothing takes account of your circumstances or objectives, and nothing is a recommendation. If you are unsure, seek advice from someone authorised to give it.",
      },
    ],
  },
  {
    title: "Market data",
    items: [
      {
        question: "Are the prices real?",
        answer:
          "Not in demo mode. A built-in simulation engine advances a stored price with a mean-reverting random walk, and every screen that shows a price labels it as simulated. Historical candles are generated the same way.",
      },
      {
        question: "Can real market data be connected?",
        answer:
          "Yes. The market-data layer is an interface with a single implementation today. Adding a licensed provider — Polygon, Finnhub, Twelve Data or another — means writing one more implementation of that interface and pointing an environment variable at it. Nothing in the interface or the trading engine changes.",
      },
      {
        question: "Why does the price move when I reload the page?",
        answer:
          "The demo engine advances the stored quote when it is read, so every user, the portfolio valuation and the order engine all agree on one price. The tick rate is deliberately modest so charts stay readable.",
      },
    ],
  },
  {
    title: "Money and trading",
    items: [
      {
        question: "Can I deposit or withdraw real money?",
        answer:
          "No. Demo mode has no connection to any payment rail, and the database function behind funding refuses to run when demo mode is switched off. Real money movement requires integrating a regulated payment provider and completing the compliance work that goes with it.",
      },
      {
        question: "Are my orders sent to an exchange?",
        answer:
          "No. Orders execute against the demo venue inside the application. No order is routed to any exchange, broker or clearing house, and no real security is bought or sold.",
      },
      {
        question: "What order types are supported?",
        answer:
          "Market, limit, stop and stop-limit, with day, good-till-cancelled, immediate-or-cancel and fill-or-kill time in force. Non-marketable orders rest until the price is reached, and reserve buying power while they do.",
      },
      {
        question: "How is my portfolio value calculated?",
        answer:
          "From your actual holdings and the current quote, on every request. Market value is quantity times price; unrealised P/L is (price minus average cost) times quantity; total value adds cash and any open strategy allocations. Nothing is stored pre-computed.",
      },
    ],
  },
  {
    title: "Investing",
    items: [
      {
        question: "Are the target returns guaranteed?",
        answer:
          "No. Every target return on the platform is an illustrative projection based on simulated data. Projections are not promises. The value of investments can fall as well as rise, and you may get back less than you put in.",
      },
      {
        question: "Is the performance history on a strategy page real?",
        answer:
          "No. It is generated by a seeded simulator so that a given strategy always produces the same illustrative shape at its stated risk level. It does not represent any real portfolio or any real investor's result, and each chart says so.",
      },
      {
        question: "Can I withdraw from a strategy early?",
        answer:
          "Terms vary and are stated on each strategy page. In demo mode all values are simulated.",
      },
    ],
  },
  {
    title: "Vehicles",
    items: [
      {
        question: "Can I really order a vehicle here?",
        answer:
          "No. The vehicle section is an independent demo marketplace. Submitting a configuration records a request against your account so you can follow the flow end to end. It is not a purchase, no payment is taken, no vehicle is reserved, and nothing is sent to any manufacturer or dealer system.",
      },
      {
        question: "Are the vehicle prices and specifications accurate?",
        answer:
          "They are illustrative figures for this demo marketplace and should not be relied on as manufacturer specifications or pricing. Vehicle images are stylised illustrations, not photographs of any actual vehicle.",
      },
    ],
  },
  {
    title: "Security and data",
    items: [
      {
        question: "How is my data protected?",
        answer:
          "Authorisation is enforced in the database with PostgreSQL Row Level Security, not just in the interface. Every table is deny-by-default and scoped to your own user id, so one account can never read another's rows. Money movement happens only inside audited transactional functions, and administrative actions are written to an append-only log.",
      },
      {
        question: "Is two-factor authentication available?",
        answer:
          "The account model and the identity provider both support it, but enrolment is not switched on in demo mode — it would lock demo accounts out of a simulated environment with no recovery path. It is on the production checklist.",
      },
      {
        question: "Will BrokerT ever ask for my password?",
        answer:
          "Never. No one from BrokerT will ask for your password or any part of it, by email, in a support ticket or anywhere else.",
      },
    ],
  },
];

export default function FaqPage() {
  return (
    <>
      <Section className="border-t-0">
        <SectionHeading
          eyebrow="FAQ"
          title="Questions, answered plainly"
          description="If something below is still unclear, ask us directly — we would rather explain it than have you assume."
          align="center"
        />
      </Section>

      {GROUPS.map((group, index) => (
        <Section key={group.title} className={index % 2 === 1 ? "bg-muted/25" : undefined}>
          <div className="mx-auto max-w-3xl">
            <h2 className="text-lg font-semibold tracking-tight">{group.title}</h2>
            <FaqAccordion items={group.items} className="mt-5" />
          </div>
        </Section>
      ))}

      <Section>
        <div className="mx-auto max-w-3xl rounded-2xl border border-border bg-card px-6 py-10 text-center">
          <h2 className="text-xl font-semibold tracking-tight">Still have a question?</h2>
          <p className="mx-auto mt-2 max-w-lg text-sm leading-relaxed text-muted-foreground">
            Signed-in customers can open a support ticket and follow the conversation in their account.
          </p>
          <div className="mt-6 flex flex-wrap justify-center gap-3">
            <Button asChild>
              <Link href="/contact">Contact us</Link>
            </Button>
            <Button asChild variant="outline">
              <Link href="/risk-disclosure">Read the risk disclosure</Link>
            </Button>
          </div>
        </div>
      </Section>
    </>
  );
}
