import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, type LegalSection } from "@/components/marketing/legal-page";
import { APP } from "@/lib/config";

export const metadata: Metadata = {
  title: "Terms of service",
  description: "The terms on which you may use BrokerT.",
};

const SECTIONS: LegalSection[] = [
  {
    heading: "Who we are, and who we are not",
    body: (
      <>
        <p>
          {APP.name} is operated by {APP.legalName} (&quot;we&quot;, &quot;us&quot;). We are an
          independent platform. {APP.trademarkNotice}
        </p>
        <p>
          We are not a registered broker-dealer, investment adviser, bank, money transmitter or payment
          institution. We are not regulated, licensed or insured, and we do not hold client money.
        </p>
      </>
    ),
  },
  {
    heading: "Accepting these terms",
    body: (
      <p>
        By creating an account or using the platform you agree to these terms, our{" "}
        <Link href="/privacy" className="font-medium text-primary hover:underline">privacy policy</Link>{" "}
        and our{" "}
        <Link href="/risk-disclosure" className="font-medium text-primary hover:underline">risk disclosure</Link>.
        If you do not agree, do not use the platform.
      </p>
    ),
  },
  {
    heading: "Demo mode and simulated data",
    body: (
      <>
        <p>
          The platform currently operates in demo mode. In demo mode:
        </p>
        <ul>
          <li>All prices, quotes and price history are generated by a simulation and are not market data.</li>
          <li>All balances are records inside the application and do not represent money held anywhere.</li>
          <li>All orders execute against a simulated venue. No order is routed to any exchange or broker, and no security is bought or sold.</li>
          <li>All investment allocations, values and returns are simulated.</li>
          <li>All vehicle order requests are simulated and reach no manufacturer or dealer.</li>
        </ul>
        <p>
          You must not rely on anything shown in demo mode as market data, as a record of any asset you
          own, or as evidence of any transaction.
        </p>
      </>
    ),
  },
  {
    heading: "Eligibility and your account",
    body: (
      <>
        <p>
          You must be at least 18 and legally able to enter into a contract. You must give accurate
          registration details and keep them current.
        </p>
        <p>
          You are responsible for your credentials and for everything done through your account. Tell us
          immediately if you believe someone else has reached it. We will never ask for your password.
        </p>
        <p>
          One person, one account. Do not share your account or let anyone else use it.
        </p>
      </>
    ),
  },
  {
    heading: "Acceptable use",
    body: (
      <>
        <p>You must not:</p>
        <ul>
          <li>Use the platform for anything unlawful, or to launder money or finance any offence.</li>
          <li>Attempt to access another user&apos;s data, or to bypass any access control.</li>
          <li>Probe, scan or test the security of the platform without our prior written consent.</li>
          <li>Scrape, mirror or resell platform data, or use it to build a competing service.</li>
          <li>Automate access in a way that degrades the service for others.</li>
          <li>Misrepresent the platform as regulated, licensed, insured, or affiliated with any vehicle manufacturer.</li>
        </ul>
      </>
    ),
  },
  {
    heading: "No advice",
    body: (
      <p>
        Nothing on the platform is investment, tax or legal advice, and nothing is a recommendation or an
        offer to buy or sell any security. We do not assess suitability or appropriateness for you.
        Decisions you make are yours alone. If you are unsure, take advice from someone authorised to
        give it.
      </p>
    ),
  },
  {
    heading: "Projections and targets",
    body: (
      <p>
        Where the platform shows a target return, a projection or an illustrative value, it is exactly
        that: an illustration, generated from simulated data. It is not a promise, a guarantee or a
        forecast, and it does not create any obligation on us. Past performance — real or simulated —
        does not indicate future results.
      </p>
    ),
  },
  {
    heading: "Availability and changes",
    body: (
      <>
        <p>
          We do not promise the platform will be available without interruption. We may change, suspend
          or withdraw any part of it, and we may change these terms. Where a change materially affects
          you we will give notice through the platform.
        </p>
        <p>
          We may suspend or close an account that breaches these terms, or where we are required to.
          Where we do, we will tell you the reason unless we are prevented from doing so.
        </p>
      </>
    ),
  },
  {
    heading: "Intellectual property",
    body: (
      <p>
        The platform, its design and its content belong to us or our licensors, except for third-party
        trademarks referenced nominatively. You may use the platform for your own purposes; you may not
        copy, adapt or redistribute it.
      </p>
    ),
  },
  {
    heading: "Liability",
    body: (
      <>
        <p>
          Nothing in these terms excludes liability that cannot lawfully be excluded, including liability
          for fraud, or for death or personal injury caused by negligence.
        </p>
        <p>
          Subject to that, we are not liable for investment losses, for loss of profit or opportunity, or
          for any indirect or consequential loss. The platform is provided &quot;as is&quot; in demo mode,
          and the data in it is simulated.
        </p>
      </>
    ),
  },
  {
    heading: "Governing law and disputes",
    body: (
      <p>
        These terms are governed by the law of the jurisdiction in which {APP.legalName} is established,
        and disputes are subject to the exclusive jurisdiction of its courts. This is a template
        provision: a live deployment must set the governing law and dispute-resolution mechanism to match
        where it actually operates and where its customers are.
      </p>
    ),
  },
  {
    heading: "Contact",
    body: (
      <p>
        Questions about these terms:{" "}
        <a href={`mailto:${APP.supportEmail}`} className="font-medium text-primary hover:underline">
          {APP.supportEmail}
        </a>
        .
      </p>
    ),
  },
];

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of service"
      updated="30 August 2026"
      intro={
        <p>
          These terms govern your use of {APP.name}. Please read them alongside our privacy policy and
          risk disclosure. This document is a template for a demo platform and is not legal advice; a
          live deployment must have it reviewed by a qualified lawyer in each market it serves.
        </p>
      }
      sections={SECTIONS}
    />
  );
}
