import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, type LegalSection } from "@/components/marketing/legal-page";
import { APP } from "@/lib/config";

export const metadata: Metadata = {
  title: "Privacy policy",
  description: "What data BrokerT collects, why, and what you can do about it.",
};

const SECTIONS: LegalSection[] = [
  {
    heading: "What this covers",
    body: (
      <p>
        This policy explains what personal data {APP.legalName} collects when you use {APP.name}, why we
        collect it, how long we keep it and what rights you have. It applies to the platform and to
        emails we send you about it.
      </p>
    ),
  },
  {
    heading: "What we collect",
    body: (
      <>
        <p>Data you give us:</p>
        <ul>
          <li>Account details: first and last name, email address, phone number and country.</li>
          <li>Profile details: an optional profile picture URL and your display preferences.</li>
          <li>Delivery details you enter when configuring a vehicle order request.</li>
          <li>The content of support tickets and messages you send us.</li>
        </ul>
        <p>Data generated by your use of the platform:</p>
        <ul>
          <li>Orders, holdings, allocations, transactions and vehicle order requests.</li>
          <li>Notifications sent to you and whether you have read them.</li>
          <li>Sign-in events, including the time, IP address and browser user-agent string.</li>
        </ul>
        <p>
          We do not collect identity documents, bank details or payment card details, because demo mode
          has no payment integration and no identity-verification provider connected.
        </p>
      </>
    ),
  },
  {
    heading: "Why we use it",
    body: (
      <ul>
        <li>To create and operate your account, and to authenticate you.</li>
        <li>To provide the platform: place and track orders, value your portfolio, record allocations and requests.</li>
        <li>To keep the account secure: detect suspicious sign-ins and tell you about security-relevant changes.</li>
        <li>To answer your support requests.</li>
        <li>To send service emails you have not turned off, and product emails only if you opt in.</li>
      </ul>
    ),
  },
  {
    heading: "Legal bases",
    body: (
      <p>
        Where data-protection law requires a legal basis, we rely on performance of our contract with you
        (operating your account), our legitimate interests (securing the platform, preventing abuse) and
        your consent (product emails, which you can withdraw at any time in{" "}
        <Link href="/settings" className="font-medium text-primary hover:underline">settings</Link>).
      </p>
    ),
  },
  {
    heading: "Who can see your data",
    body: (
      <>
        <p>
          Other customers cannot see your data. Access is restricted in the database itself with Row Level
          Security: each row is scoped to the account that owns it, and the platform does not rely on the
          interface to enforce that.
        </p>
        <p>
          Our administrators can see customer records where their role permits it. Every administrative
          change is written to an append-only audit log recording who made it and when.
        </p>
        <p>
          We use service providers to run the platform — a database and authentication provider, a
          hosting provider, and an email provider if one is configured. They process data on our
          instructions. We do not sell personal data.
        </p>
      </>
    ),
  },
  {
    heading: "Cookies and similar technologies",
    body: (
      <p>
        We set cookies that are strictly necessary to keep you signed in and to protect the session. We do
        not use advertising cookies or third-party analytics trackers. Your theme preference is stored
        locally in your browser and on your account.
      </p>
    ),
  },
  {
    heading: "How long we keep it",
    body: (
      <ul>
        <li>Account and profile data: while your account exists, and then as long as we must for legal or accounting reasons.</li>
        <li>Transaction and order records: retained as records of activity on the platform.</li>
        <li>Sign-in events: a rolling recent history, shown to you on the security page.</li>
        <li>Support tickets: retained so we have context if you contact us again.</li>
      </ul>
    ),
  },
  {
    heading: "Your rights",
    body: (
      <>
        <p>
          Depending on where you live you may have the right to access your data, correct it, delete it,
          restrict or object to how we use it, and to receive a copy in a portable format. You can also
          complain to your data-protection authority.
        </p>
        <p>
          You can edit most of your data directly in{" "}
          <Link href="/profile" className="font-medium text-primary hover:underline">your profile</Link>.
          For anything else, contact us.
        </p>
      </>
    ),
  },
  {
    heading: "Security",
    body: (
      <>
        <p>
          Passwords are handled by our authentication provider and are never stored by the application.
          Authorisation is enforced at the database level. Privileged credentials are held server-side and
          are never exposed to the browser.
        </p>
        <p>
          No system is perfectly secure. Use a password you do not use anywhere else, and tell us
          immediately if you suspect your account has been reached by someone else.
        </p>
      </>
    ),
  },
  {
    heading: "International transfers and children",
    body: (
      <>
        <p>
          Our providers may process data outside your country. A live deployment must document those
          transfers and put an appropriate safeguard in place for each.
        </p>
        <p>The platform is not for anyone under 18, and we do not knowingly collect their data.</p>
      </>
    ),
  },
  {
    heading: "Changes and contact",
    body: (
      <p>
        We will post any change to this policy here and, where the change is material, tell you through
        the platform. Questions or requests:{" "}
        <a href={`mailto:${APP.supportEmail}`} className="font-medium text-primary hover:underline">
          {APP.supportEmail}
        </a>
        .
      </p>
    ),
  },
];

export default function PrivacyPage() {
  return (
    <LegalPage
      title="Privacy policy"
      updated="30 August 2026"
      intro={
        <p>
          What we collect, why, and what you can do about it. This document is a template for a demo
          platform and is not legal advice; a live deployment must have it reviewed against the
          data-protection law of each market it serves.
        </p>
      }
      sections={SECTIONS}
    />
  );
}
