import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, type LegalSection } from "@/components/marketing/legal-page";
import { APP } from "@/lib/config";

export const metadata: Metadata = {
  title: "Risk disclosure",
  description:
    "The risks of investing, of holding a concentrated single-issuer position, and of relying on simulated data.",
};

const SECTIONS: LegalSection[] = [
  {
    heading: "Capital is at risk",
    body: (
      <>
        <p>
          Investing involves risk, including the possible loss of principal. The value of investments can
          fall as well as rise, and you may get back less than you put in — up to and including everything
          you put in.
        </p>
        <p>
          Past performance does not guarantee future results. This is true of real performance and of the
          simulated performance shown throughout this platform.
        </p>
      </>
    ),
  },
  {
    heading: "Concentration risk",
    body: (
      <>
        <p>
          {APP.name} is built around a single instrument. A portfolio concentrated in one issuer carries
          that issuer&apos;s full idiosyncratic risk: a single delivery figure, product decision,
          regulatory ruling or executive change can move the entire position with nothing to offset it.
        </p>
        <p>
          There is no diversification benefit in a single-issuer position and no downside protection.
          Consider carefully how such a position sits alongside everything else you hold.
        </p>
      </>
    ),
  },
  {
    heading: "Volatility",
    body: (
      <p>
        The instrument covered by this platform has historically been among the most volatile
        large-capitalisation equities in the US market, with drawdowns exceeding 50% from peak to trough.
        Volatility of that order is not an anomaly for this instrument; it is a normal feature of it.
      </p>
    ),
  },
  {
    heading: "Simulated data",
    body: (
      <>
        <p>
          In demo mode every price, chart, balance, order fill, allocation value and strategy track record
          on this platform is generated by a simulation. None of it is market data, and none of it
          describes a real position, a real transaction or a real return.
        </p>
        <p>
          Simulated data is smoother and better behaved than a real market. Do not use it to judge how a
          strategy would have performed, to size a real position, or to test a real trading approach.
        </p>
      </>
    ),
  },
  {
    heading: "Projections are not promises",
    body: (
      <p>
        Every target return, projected value and illustrative figure on this platform is exactly that: an
        illustration. It is not guaranteed, promised or assured, it creates no obligation on us, and the
        actual outcome may be materially worse — including a total loss.
      </p>
    ),
  },
  {
    heading: "Market data may be delayed",
    body: (
      <p>
        Where real market data is connected, it may be delayed relative to the exchange and may contain
        errors or gaps. Prices shown at the moment you place an order may differ from the price at which
        the order executes.
      </p>
    ),
  },
  {
    heading: "Liquidity and execution",
    body: (
      <ul>
        <li>Market orders execute at the prevailing price, which may be worse than the estimate shown.</li>
        <li>Limit and stop orders may not execute at all if the market does not reach your price.</li>
        <li>Some investment strategies are illiquid and may commit your capital for a fixed term with no ability to exit early.</li>
      </ul>
    ),
  },
  {
    heading: "Fees reduce returns",
    body: (
      <p>
        Commissions, regulatory fees, management fees and performance fees all reduce what you keep. The
        full schedule is on our{" "}
        <Link href="/pricing" className="font-medium text-primary hover:underline">pricing page</Link>, and
        strategy-specific fees are stated on each strategy page.
      </p>
    ),
  },
  {
    heading: "No advice, no protection scheme",
    body: (
      <>
        <p>
          Nothing on this platform is investment advice or a recommendation, and we do not assess whether
          anything is suitable or appropriate for you.
        </p>
        <p>
          {APP.legalName} is not regulated, licensed or insured, and holds no client money. No investor
          compensation scheme, deposit guarantee or similar protection applies to anything on this
          platform.
        </p>
      </>
    ),
  },
  {
    heading: "No affiliation",
    body: <p>{APP.trademarkNotice}</p>,
  },
  {
    heading: "If you are unsure",
    body: (
      <p>
        Take independent advice from someone authorised to give it in your jurisdiction before making any
        investment decision. Never invest money you cannot afford to lose.
      </p>
    ),
  },
];

export default function RiskDisclosurePage() {
  return (
    <LegalPage
      title="Risk disclosure"
      updated="30 August 2026"
      intro={
        <p>
          Read this before allocating anything, real or simulated. It sets out the risks of investing in
          general, of a concentrated single-issuer position, and of relying on the simulated data this
          platform shows.
        </p>
      }
      sections={SECTIONS}
    />
  );
}
