import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { PageHeader } from "@/components/shared/page-header";
import { StatCard } from "@/components/shared/stat-card";
import { StatusBadge } from "@/components/shared/status-badge";
import { CopyButton } from "@/components/shared/copy-button";
import { RiskMeter } from "@/components/shared/risk-meter";
import { RiskAlert } from "@/components/shared/demo-notices";
import { PerformanceChart } from "@/components/portfolio/performance-chart";
import { getMyInvestmentPosition } from "@/lib/services/investments";
import { measureInvestmentPosition } from "@/lib/calculations/investments";
import { simulateStrategyHistory } from "@/lib/simulation";
import { formatCurrency, formatDate, formatPercent } from "@/lib/format";
import { requireSession } from "@/lib/auth";

export const dynamic = "force-dynamic";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> {
  const { id } = await params;
  const position = await getMyInvestmentPosition(id);
  return { title: position ? `Allocation ${position.reference}` : "Allocation" };
}

export default async function AllocationDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  await requireSession(`/investments/active/${id}`);

  const position = await getMyInvestmentPosition(id);
  if (!position) notFound();

  const metrics = measureInvestmentPosition({
    principal: Number(position.principal),
    currentValue: Number(position.current_value),
    targetReturnPct: Number(position.target_return_pct),
    startDate: position.start_date,
    targetDate: position.target_date,
  });

  // The strategy's illustrative track record, rebased to this allocation.
  const history = simulateStrategyHistory({
    seed: `${position.investments?.slug ?? "strategy"}-${position.reference}`,
    months: Math.max(Math.round(metrics.totalDays / 30), 6),
    annualReturnPct: Number(position.target_return_pct),
    riskLevel: position.investments?.risk_level ?? "balanced",
    startValue: metrics.principal,
  });

  return (
    <div className="space-y-5">
      <Button asChild variant="ghost" size="sm" className="-ml-2">
        <Link href="/investments/active">
          <ArrowLeft /> My allocations
        </Link>
      </Button>

      <PageHeader
        title={position.investments?.name ?? "Allocation"}
        description={`Allocated ${formatDate(position.start_date)}`}
        actions={<CopyButton value={position.reference} label="Copy allocation reference" />}
      >
        <div className="flex flex-wrap items-center gap-2 pt-2">
          <span className="font-mono text-xs text-muted-foreground">{position.reference}</span>
          <StatusBadge status={position.status} />
          {position.is_simulated && <Badge variant="warning">Simulated</Badge>}
          {position.investments && <RiskMeter level={position.investments.risk_level} />}
        </div>
      </PageHeader>

      <section aria-label="Allocation summary" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatCard label="Principal" value={formatCurrency(metrics.principal)} />
        <StatCard label="Current value" value={formatCurrency(metrics.currentValue)} accent="primary" />
        <StatCard
          label="Gain / loss"
          value={formatCurrency(metrics.gain, { signed: true })}
          change={metrics.gain}
          changePercent={metrics.gainPercent}
          changeFormat="currency"
          accent={metrics.gain >= 0 ? "gain" : "loss"}
        />
        <StatCard
          label="Illustrative value at target"
          value={formatCurrency(metrics.projectedValue)}
          hint="A projection, not a guarantee"
        />
      </section>

      <div className="grid gap-5 lg:grid-cols-3">
        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle>Simulated value over the term</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            <PerformanceChart points={history} height={240} />
            <p className="rounded-lg border border-warning/30 bg-warning/8 px-3 py-2.5 text-xs leading-relaxed">
              <strong className="font-medium">Simulated.</strong> This series is generated by the demo
              engine for illustration. It does not represent a real holding or a real return.
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Term progress</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-1.5">
              <div className="flex items-center justify-between text-xs text-muted-foreground">
                <span>{formatPercent(metrics.progressPercent, { signed: false })} elapsed</span>
                <span className="tabular">{metrics.daysRemaining} days left</span>
              </div>
              <Progress value={metrics.progressPercent} />
            </div>

            <dl className="divide-y divide-border">
              {[
                ["Start date", formatDate(position.start_date)],
                ["Target date", formatDate(position.target_date)],
                ["Term", `${metrics.totalDays} days`],
                ["Elapsed", `${metrics.daysElapsed} days`],
                ["Target return", formatPercent(Number(position.target_return_pct), { signed: false })],
                ["Category", position.investments?.category ?? "—"],
              ].map(([label, value]) => (
                <div key={label} className="flex items-center justify-between gap-4 py-2.5 text-sm">
                  <dt className="text-muted-foreground">{label}</dt>
                  <dd className="font-medium tabular">{value}</dd>
                </div>
              ))}
            </dl>

            {position.investments && (
              <Button asChild variant="outline" size="sm" className="w-full">
                <Link href={`/investments/${position.investments.slug}`}>View strategy</Link>
              </Button>
            )}
          </CardContent>
        </Card>
      </div>

      <RiskAlert />
    </div>
  );
}
